package Client.Gui;

import Client.Client;
import Communication.Messages.BidMessage;
import Infomation.Auction;
import Infomation.Bid;
import Infomation.Item;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;

/**
 * Created by mark on 15/05/15.
 */
public class AuctionView {
    private JLabel AuctionItemName;
    private JTextArea AuctionItemDesc;
    private JButton bidButton;
    private JTextField BidAmount;
    private JList AuctionBids;
    private JPanel MainPanel;

    public AuctionView(final Auction auction, final Client client) {
        Item item = auction.getItem();
        AuctionItemName.setText(item.getTitle());
        AuctionItemDesc.setText(item.getDesc());
        DefaultListModel listModel = new DefaultListModel();
        for (Bid bid : auction) {
            listModel.addElement(bid);
        }
        AuctionBids.setModel(listModel);

        bidButton.addActionListener(new ActionListener() {
            private Auction a = auction;
            private Client c = client;

            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                BigDecimal bidAmount = new BigDecimal(Double.parseDouble(BidAmount.getText()));
                if (bidAmount.compareTo(auction.getHighestBid().getAmount()) > 0) {
                    Bid bid = new Bid(client.getUser(), bidAmount, auction);
                    c.getComms().sendMessage(new BidMessage(bid));
                }
            }
        });

        JFrame frame = new JFrame("ClientGui");
        frame.setContentPane(MainPanel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        MainPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        BidAmount = new JTextField();
        BidAmount.setText("Enter Bid Here");
        MainPanel.add(BidAmount, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        bidButton = new JButton();
        bidButton.setText("Bid");
        MainPanel.add(bidButton, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        AuctionItemName = new JLabel();
        AuctionItemName.setEnabled(true);
        AuctionItemName.setText("Label");
        MainPanel.add(AuctionItemName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        AuctionItemDesc = new JTextArea();
        AuctionItemDesc.setEditable(false);
        AuctionItemDesc.setEnabled(true);
        MainPanel.add(AuctionItemDesc, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        AuctionBids = new JList();
        AuctionBids.setEnabled(false);
        MainPanel.add(AuctionBids, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
